package com.megaman.game.world;

public enum BodySense {
    BODY_IN_WATER,
    HIT_BY_HEAD,
    FEET_ON_GROUND,
    FEET_ON_ICE,
    HEAD_TOUCHING_BLOCK,
    SIDE_TOUCHING_BLOCK_LEFT,
    SIDE_TOUCHING_BLOCK_RIGHT,
    SIDE_TOUCHING_ICE_LEFT,
    SIDE_TOUCHING_ICE_RIGHT,
    HEAD_TOUCHING_LADDER,
    FEET_TOUCHING_LADDER
}
